shoes-spot/app.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from config import Config

db = SQLAlchemy()
from services.catalog_service import Product
from services.order_service import Order, OrderItem
from services.auth_service import User
from services.cart_service import CartItem

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)

    from controllers.auth_controller import auth_bp
    from controllers.catalog_controller import catalog_bp
    from controllers.cart_controller import cart_bp

    app.register_blueprint(auth_bp)
    app.register_blueprint(cart_bp)
    app.register_blueprint(catalog_bp)

    @app.route("/")
    def index():
        return render_template("index.html")

    return app

if __name__ == "__main__":
    app = create_app()

    with app.app_context():
        db.create_all()
    app.run(debug=True)

shoes-spot/controllers/auth_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from services.auth_service import register_user, authenticate_user

auth_bp = Blueprint("auth", __name__, url_prefix="/auth")

@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        if register_user(email, password):
            flash("Регистрация успешна! Можете да влезете в профила си.", "success")
            return redirect(url_for("auth.login"))
        else:
            flash("Този имейл вече е регистриран.", "error")

    return render_template("register.html")


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = authenticate_user(email, password)
        if user:
            session["user"] = user
            return redirect(url_for("catalog.catalog"))
        else:
            flash("Грешен имейл или парола.", "error")

    return render_template("login.html")


@auth_bp.route("/logout")
def logout():
    session.pop("user", None)
    flash("Излязохте успешно.", "success")
    return render_template("index.html")

shoes-spot/controllers/cart_controller.py
from flask import Blueprint, session, redirect, url_for, render_template, flash, request
from services.catalog_service import get_product_by_id, update_product_stock
from services.cart_service import add_to_cart, get_cart, clear_cart, CartItem
from app import db

cart_bp = Blueprint("cart", __name__, url_prefix="/cart")


@cart_bp.route('/')
def view_cart():
    user = session.get("user")
    if not user:
        flash("Моля, влезте в профила си, за да видите количката.", "error")
        return redirect(url_for("auth.login"))

    username = user["email"]
    cart_items = get_cart(username)

    if not cart_items:
        flash("Кошницата е празна.", "info")
        return render_template("cart.html", items=[], total=0)

    total = sum(item.price * item.quantity for item in cart_items)
    return render_template("cart.html", items=cart_items, total=total)


@cart_bp.route('/add/<int:product_id>')
def add_to_cart_route(product_id):
    user = session.get("user")
    if not user:
        flash("Моля, влезте в профила си, за да добавяте продукти.", "error")
        return redirect(url_for("auth.login"))

    product = get_product_by_id(product_id)
    if not product:
        flash("Продуктът не съществува.", "error")
        return redirect(url_for("catalog.catalog"))

    add_to_cart(user["email"], product, 1)
    flash(f"{product.name} беше добавен в кошницата.", "success")
    return redirect(url_for("catalog.catalog"))


@cart_bp.route('/remove/<int:product_id>')
def remove_from_cart(product_id):
    user = session.get("user")
    if not user:
        return redirect(url_for("auth.login"))

    username = user["email"]

    item = CartItem.query.filter_by(username=username, product_id=product_id).first()
    if item:
        db.session.delete(item)
        db.session.commit()
        flash("Продуктът беше премахнат от кошницата.", "success")
    else:
        flash("Продуктът не е намерен в количката.", "error")

    return redirect(url_for("cart.view_cart"))

@cart_bp.route('/clear')
def clear_cart_route():
    user = session.get("user")
    if not user:
        return redirect(url_for("auth.login"))

    clear_cart(user["email"])
    flash("Кошницата беше изчистена.", "success")
    return redirect(url_for("cart.view_cart"))

@cart_bp.route('/checkout', methods=["GET", "POST"])
def checkout():
    user = session.get("user")
    if not user:
        return redirect(url_for("auth.login"))

    username = user["email"]
    cart_items = get_cart(username)

    if request.method == "POST":
        address = request.form.get("address")
        payment = request.form.get("payment")

        if not cart_items:
            flash("Кошницата е празна!", "error")
            return redirect(url_for("cart.view_cart"))

        for item in cart_items:
            success = update_product_stock(item.product_id, item.quantity)
            if not success:
                flash(f"Недостатъчна наличност за {item.product_name}.", "error")
                return redirect(url_for("cart.view_cart"))

        clear_cart(username)
        flash("Поръчката е успешно направена!", "success")
        return redirect(url_for("catalog.catalog"))

    total = sum(item.price * item.quantity for item in cart_items)
    return render_template("checkout.html", items=cart_items, total=total)

shoes-spot/controllers/catalog_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from services.catalog_service import create_product, get_product_by_id, update_product, delete_product, \
    search_and_filter_products

catalog_bp = Blueprint("catalog", __name__, url_prefix="/catalog")

@catalog_bp.route("/")
def catalog():
    query = request.args.get("query")
    color = request.args.get("color")
    min_price = request.args.get("min_price", type=float)
    max_price = request.args.get("max_price", type=float)
    size = request.args.get("size", type=int)
    in_stock = request.args.get("in_stock")
    category = request.args.get("category")
    gender = request.args.get("gender")

    products = search_and_filter_products(
        query=query,
        color=color,
        min_price=min_price,
        max_price=max_price,
        size=size,
        in_stock=True if in_stock else False,
        category=category,
        gender=gender
    )

    return render_template("catalog.html", products=products)

@catalog_bp.route("/add", methods=["POST"])
def add():
    if not session.get("user") or session["user"]["role"] != "admin":
        flash("Само администратор може да добавя продукти!", "error")
        return redirect(url_for("catalog.catalog"))

    name = request.form.get("name")
    description = request.form.get("description")
    color = request.form.get("color")
    sizes = [int(s.strip()) for s in request.form.get("sizes").split(",")]
    price = float(request.form.get("price"))
    stock = int(request.form.get("stock"))
    category = request.form.get("category")
    gender = request.form.get("gender")

    create_product({
        "name": name,
        "description": description,
        "color": color,
        "sizes": sizes,
        "price": price,
        "stock": stock,
        "category": category,
        "gender": gender
    })

    flash("Продуктът беше добавен успешно!", "success")
    return redirect(url_for("catalog.catalog"))


@catalog_bp.route("/edit/<int:product_id>", methods=["POST"])
def edit(product_id):
    if not session.get("user") or session["user"]["role"] != "admin":
        flash("Само администратор може да редактира продукти!", "error")
        return redirect(url_for("catalog.catalog"))

    new_data = {
        "name": request.form.get("name"),
        "description": request.form.get("description"),
        "color": request.form.get("color"),
        "sizes": [int(s.strip()) for s in request.form.get("sizes").split(",")],
        "price": float(request.form.get("price")),
        "stock": int(request.form.get("stock")),
        "category": request.form.get("category"),
        "gender": request.form.get("gender")
    }
    update_product(product_id, new_data)
    flash("Продуктът е редактиран!", "success")
    return redirect(url_for("catalog.catalog"))

@catalog_bp.route("/delete/<int:product_id>")
def delete(product_id):
    if not session.get("user") or session["user"]["role"] != "admin":
        flash("Само администратор може да изтрива продукти!", "error")
        return redirect(url_for("catalog.catalog"))

    delete_product(product_id)
    flash("Продуктът е изтрит!", "info")
    return redirect(url_for("catalog.catalog"))

shoes-spot/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Flask App{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
  <nav>
    {% if session.get('user') %}
  <a href="{{ url_for('catalog.catalog') }}">Каталог</a>

  {% if session.user.role == 'user' %}
    <a href="{{ url_for('cart.view_cart') }}">Кошница</a>
  {% endif %}

  <a href="{{ url_for('auth.logout') }}">Изход</a>
{% else %}
  <a href="{{ url_for('index') }}">Начало</a>
  <a href="{{ url_for('auth.login') }}">Вход</a>
  <a href="{{ url_for('auth.register') }}">Регистрация</a>
{% endif %}

  </nav>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <ul class="flashes">
        {% for category, message in messages %}
          <li class="{{ category }}">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  {% endwith %}

  {% block content %}{% endblock %}
</body>
</html>

shoes-spot/templates/cart.html
{% extends "base.html" %}
{% block title %}Кошница{% endblock %}

{% block content %}
<h2>Кошница</h2>

{% if items %}
<table>
    <tr>
        <th>Продукт</th>
        <th>Цена</th>
        <th>Количество</th>
        <th>Сума</th>
    </tr>
{% for item in items %}
  <tr>
    <td>{{ item.product_name }}</td>
    <td>{{ item.quantity }}</td>
    <td>{{ item.price }}</td>
    <td>{{ item.quantity * item.price }}</td>
  </tr>
{% endfor %}
</table>

<p><strong>Общо сума: {{ total }} лв.</strong></p>

<form action="{{ url_for('cart.clear_cart_route') }}" method="GET" style="display:inline;">
    <button type="submit">Изчисти кошницата</button>
</form>

<a href="{{ url_for('cart.checkout') }}">
    <button type="submit">Поръчай</button>
</a>

{% else %}
<p>Кошницата е празна.</p>
{% endif %}
{% endblock %}

shoes-spot/templates/catalog.html
{% extends "base.html" %}
{% block title %}Каталог{% endblock %}
{% block content %}

<h2>Търсене на обувки</h2>
<form method="GET" action="{{ url_for('catalog.catalog') }}">
    <input type="text" name="query" placeholder="Търси по име или цвят" value="{{ request.args.get('query', '') }}">
    <button type="submit">Търси</button>
</form>
<br><br>
<hr>

<h2>Филтриране на обувки</h2>
<form method="GET" action="{{ url_for('catalog.catalog') }}" style="margin-top: 10px;">
    <input type="number" step="0.01" name="min_price" placeholder="Мин. цена" value="{{ request.args.get('min_price', '') }}">
    <input type="number" step="0.01" name="max_price" placeholder="Макс. цена" value="{{ request.args.get('max_price', '') }}">
    <input type="number" name="size" placeholder="Размер" value="{{ request.args.get('size') }}">
    <label><input type="checkbox" name="in_stock" {% if request.args.get('in_stock') %}checked{% endif %}> Само налични</label>

    <select name="category">
        <option value="">Всички категории</option>
        <option value="sport" {% if request.args.get('category') == 'sport' %}selected{% endif %}>Спортни обувки</option>
        <option value="formal" {% if request.args.get('category') == 'formal' %}selected{% endif %}>Официални обувки</option>
        <option value="casual" {% if request.args.get('category') == 'casual' %}selected{% endif %}>Ежедневни обувки</option>
    </select>

    <select name="gender">
        <option value="">Всички</option>
        <option value="men" {% if request.args.get('gender') == 'men' %}selected{% endif %}>Мъже</option>
        <option value="women" {% if request.args.get('gender') == 'women' %}selected{% endif %}>Жени</option>
        <option value="unisex" {% if request.args.get('gender') == 'unisex' %}selected{% endif %}>Unisex</option>
    </select>

    <button type="submit">Филтрирай</button>
</form>

<br><br>
<hr>

<h2>Каталог с обувки</h2>

<div class="product-grid">
    {% for product in products %}
    <div class="product-card">

        <img src="{{ url_for('static', filename='images/' + (product.image if product.image else (product.name.replace(' ', '_') + '.webp'))) }}"
         alt="{{ product.name }}"
         onerror="this.onerror=null; this.src='{{ url_for('static', filename='images/no-image.webp') }}';">

        {% if session.get('user') and session['user']['role'] == 'admin' %}
        <form method="POST" action="{{ url_for('catalog.edit', product_id=product.id) }}">
            <input type="text" name="name" value="{{ product.name }}">
            <input type="text" name="description" value="{{ product.description }}">
            <input type="text" name="color" value="{{ product.color }}">
            <input type="text" name="sizes" value="{{ product.sizes }}">
            <input type="number" step="0.01" name="price" value="{{ product.price }}">
            <input type="number" name="stock" value="{{ product.stock }}">
            <input type="text" name="category" value="{{ product.category }}">
            <input type="text" name="gender" value="{{ product.gender }}">
            <div class="actions">
                <button type="submit">Запази</button>
                <a href="{{ url_for('catalog.delete', product_id=product.id) }}">Изтрий</a>
            </div>
        </form>
        {% else %}
        <h3>{{ product.name }}</h3>
        <p>{{ product.description }}</p>
        <p><b>Цвят:</b> {{ product.color }}</p>
        <p><b>Размери:</b> {{ product.sizes}}</p>
        <p><b>Цена:</b> {{ product.price }} лв.</p>
        <p><b>Наличност:</b> {{ product.stock }}</p>
        <a href="{{ url_for('cart.add_to_cart_route', product_id=product.id) }}" class="btn">Добави в кошницата</a>
        {% endif %}
    </div>
    {% endfor %}
</div>

{% if session.get('user') and session['user']['role'] == 'admin' %}
<br><br><hr>
<h3>Добави нов продукт</h3>
<form method="POST" action="{{ url_for('catalog.add') }}">
    <input type="text" name="name" placeholder="Име" required>
    <input type="text" name="description" placeholder="Описание" required>
    <input type="text" name="color" placeholder="Цвят" required>
    <input type="text" name="sizes" placeholder="Пример: 40,41,42" required>
    <input type="number" step="0.01" name="price" placeholder="Цена" required>
    <input type="number" name="stock" placeholder="Наличност" required>
    <input type="text" name="category" placeholder="Категория (спортни/официални/ежедневни)" required>
    <input type="text" name="gender" placeholder="Пол (мъжки/женски)" required>
    <button type="submit">Добави</button>
</form>
{% endif %}
{% endblock %}

shoes-spot/templates/checkout.html
{% extends "base.html" %}
{% block title %}Поръчка{% endblock %}
{% block content %}
<h2>Финализиране на поръчка</h2>
<form method="POST">
    <label>Адрес за доставка:</label><br>
    <input type="text" name="address" required><br><br>

    <label>Метод на плащане:</label><br>
    <select name="payment" required>
        <option value="Наложен платеж">Наложен платеж</option>
        <option value="Карта">Кредитна/Дебитна карта</option>
    </select><br><br>

    <button type="submit">Потвърди поръчката</button>
</form>
{% endblock %}

shoes-spot/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<br><br><br><h1>Добре дошли в онлайн магазина за обувки Shoes spot!</h1>
<p>Моля, влезте в профила си или се регистрирайте, за да продължите напред.</p>
{% endblock %}

shoes-spot/templates/login.html
{% extends "base.html" %}
{% block title %}Вход{% endblock %}
{% block content %}

<div class="auth_container">
    <div class="card">
        <h2>Вход</h2>
        <form method="POST" class="form">
            <div class="form-group">
                <label for="email">Имейл:</label>
                <input type="email" id="email" name="email" required>
            </div>

            <div class="form-group">
                <label for="password">Парола:</label>
                <input type="password" id="password" name="password" required>
            </div>

            <button type="submit" class="btn">Влез</button>
        </form>
    </div>
</div>

{% endblock %}

shoes-spot/templates/register.html
{% extends "base.html" %}
{% block title %}Регистрация{% endblock %}
{% block content %}

<div class="auth_container">
    <div class="card">
        <h2>Регистрация</h2>
        <form method="POST" class="form">
            <div class="form-group">
                <label for="email">Имейл:</label>
                <input type="email" id="email" name="email" required>
            </div>

            <div class="form-group">
                <label for="password">Парола:</label>
                <input type="password" id="password" name="password" required>
            </div>

            <button type="submit" class="btn">Регистрирай се</button>
        </form>
    </div>
</div>

{% endblock %}